import numpy as np

"""
Since pyramidal cell are aligned in parallel, they form a dipole layer of thickness d
when they are synchronized within a cortical molecule. We identify these molecules with
teh anatomical columns in order to collective dipole field potential (as local field potential
generated by a mass of apprxoiamtely 10k pyramidal cells).
"""
